name: cypress-aquabot-testing

on: [push]

jobs:

  run-cypress-tests:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix: 
        browser: [chrome, firefox]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run - ${{ matrix.browser }}
        uses: cypress-io/github-action@v2
        with:
          install-command: yarn install
          browser: ${{ matrix.browser }}
          record: true
          wait-on: ${{ secrets.BASE_URL }}
          wait-on-timeout: 120

        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}